### ISSUE TITLE
def objectTypes

### ISSUE THREAD

**Issue by AbuBaniaz** [PURE2-Team/pure2#1]
Greetings, could you please add the following so that we can update the emergency/skin_default skin.

https://github.com/openatv/enigma2/commit/095e4d1c04bba04dc510bf49636620954154d77f

Following teams have the code
```
OpenPLI
OpenViX
OpenATV
Openvision
Team blue
OpenDroid
OpenHDF
OpenSpa
```
Thanks in advance

**Comment by terrajoe** [comment]
changes are merged in code. thx for hint!

terra
