### ISSUE TITLE
can't open the official PurE2 website

### ISSUE THREAD

**Issue by s3n0** [PURE2-Team/pure2#2]
Hi.

I wanted to test the PurE2 image, but unfortunately I can't open the official PurE2 website. There is some language selection error (in this case it is Slovakia). I'm using an updated Mozilla Firefox browser. 

I also tried http://www.pur-e2.club/OU/images/index.php , but unfortunately there is the same error.

Thanks.

![PurE2-webpage-error](https://user-images.githubusercontent.com/13181404/71898252-1c9b1f80-3159-11ea-9612-911da8857fe4.png)

**Comment by terrajoe** [comment]
i have test it and have no issue. it could be that the ip-provider make trouble. you can change you dns or you come the home of pure2: http://www.hd-digital-satcrew.com

**Comment by s3n0** [comment]
**The error is on the side of your web server.** This message is about a server error. This is not a bug of  web browser or provider :). Unfortunately, this web server responds with a error. That is why I reported the error.

The server says there is some error on the first line in the "./languages/sk.txt" file. Why don't you check this file on the web server ?!

The problem also persists when tested through other internet providers in Slovakia and other web browsers (Google Chrome). The problem is with the detection of the Slovak language. I believe that since "SK" indicates a language localization for Slovakia, the error will be somewhere in the localization or in a non-existent file.

Before you test the opening of a website in your country, please test yourself and not me, change your DNS or set up and use a free PROXY server from Slovakia, and you will get an error. Here is one example of a free PROXY server (very slow, so please be patient) that I found in Slovakia:
176.101.177.253:8080

Obviously, I tried to open the homepage http://www.hd-digital-satcrew.com , which would normally open without any problems. However, after clicking "download", I get the same error (it's the same web-page)!

Thank you for your time, guys.

**Comment by FrancHR** [comment]
Please try now!

**Comment by s3n0** [comment]
Good job. It works fine. Thanks!

**Comment by BliNeR-KeY** [comment]
hello i'm ruben from EGAMI Team.
i send you example files Json for Flash online .
https://mega.nz/file/tg1GUZyS#txpkXoDoQwTP9Bh4uarzw-CIdjIHJCXyiDEV_dTYbbM
needs to put in public_html download images folder and edit php file.

out like this. https://image.egami-image.com/json/novaler4k

Please Check, @jbleyel are upgrade Flash online Python3 code. 

https://github.com/openatv/enigma2/blob/FlashManager/lib/python/Screens/FlashManager.py

**Comment by s3n0** [comment]
@BliNeR-KeY 

Hi there ! You wrote a new post in the wrong thread (under "Closed ISSUES"). Write a "New ISSUE" or create a "Pull Request" on the PurE2 github (as first, you must, if I remember correctly, create a fork from the official github PurE2 to your github).
